### ISSUE TITLE
Sorry but there are too many bugs to use this reasonable

### ISSUE THREAD

**Issue by berlincityboy** [mccormicka/Mockgoose#143]
Remove function*s* are not working (records still exist even though the remove() has no errors) and find() calls don't give you the id of the record ( WHAT THE FUCK ).

mockgoose 2.0.3
mongoose 4.1.6

**Comment by supersam654** [comment]
Mongoose 4 isn't supported yet. My PR (#142) which just got merged into master should resolve most or all of your issues. It's not on npm yet.

**Comment by winfinit** [comment]
just published 2.1.3 to npm

**Comment by supersam654** [comment]
@winfinit Just a heads up that the latest version does not support Mongosoe 3.x anymore so you might want to bump the major version number instead.

**Comment by winfinit** [comment]
changed major version to 4, so it would match mongoose version

**Comment by winfinit** [comment]
I think that mocking database functionality is a bit tricky, because it in order to really mock it, you need to duplicate databases functionality one to one, which is unreasonable... so what are we trying to solve? unit testing or integration testing or just getting our tests kinda pass?

I feel that approach that this module was taking before is not sustainable, and i am working on a new approach, where we can use real database, without mocking a single thing, and that is our next release number 5 that is coming soon!
