### ISSUE TITLE
Store/restore db state

### ISSUE THREAD

**Issue by wmertens** [mccormicka/Mockgoose#144]
Is it possible to (un)serialize the db state? Then this would be a great alternative for mongoose during development or even for small applications.

**Comment by winfinit** [comment]
for development and test phases, you can use mongodb-prebuilt, it allows one to control mongod process from within your application, 

```javascript
var mongodb_prebuilt = require('mongodb-prebuilt');
mongodb_prebuilt.start_server({
    version: "3.0.4"
}, function(err) {
    if (!err) console.log('server started');
});
```

**Comment by wmertens** [comment]
Hmm, useful I suppose, but a lot slower than an in-memory database…

On Mon, Nov 9, 2015, 8:15 PM Roman Jurkov <notifications@github.com> wrote:

> for development and test phases, you can use mongodb-prebuilt, it allows
> one to control mongod process from within your application,
>
> var mongodb_prebuilt = require('mongodb-prebuilt');
> mongodb_prebuilt.start_server({
>     version: "3.0.4"
> }, function(err) {
>     if (!err) console.log('server started');
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mccormicka/Mockgoose/issues/144#issuecomment-155157773>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by winfinit** [comment]
I would disagree about it being slower, because what Mockgoose project started to do is to replicate functionality of a database with pure javascript, which has several issues, one of them is tons of functionality is not supported, another issue is that ported functionality has issues, either with original implementation, or misalignment with API provided by either Mongoose or mongodb-native. 

slower part that i agree with, is download portion, so original npm install would take longer (for the first time), and minimum startup time of mongod, however runtime not only clean and compliant, but also faster, since you can take advantage of mongoldb's engine.

**Comment by wmertens** [comment]
Indeed, there is a give-and-take. I must say that being able to control db
install and startup is very interesting, as it greatly simplifies app
setup. For unit tests, mockgoose wins on speed and management though.

Thanks for pointing it out!

On Mon, Nov 9, 2015, 9:03 PM Roman Jurkov <notifications@github.com> wrote:

> I would disagree about it being slower, because what Mockgoose project
> started to do is to replicate functionality of a database with pure
> javascript, which has several issues, one of them is tons of functionality
> is not supported, another issue is that ported functionality has issues,
> either with original implementation, or misalignment with API provided by
> either Mongoose or mongodb-native.
>
> slower part that i agree with, is download portion, so original npm
> install would take longer (for the first time), and minimum startup time of
> mongod, however runtime not only clean and compliant, but also faster,
> since you can take advantage of mongoldb's engine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mccormicka/Mockgoose/issues/144#issuecomment-155175459>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)
