### ISSUE TITLE
Error on dependency dtrace-provider inside bunyan

### ISSUE THREAD

**Issue by charlires** [mccormicka/Mockgoose#150]
Maybe this is not an issue from mockgoose
This is my env
Node v4.1.1
npm@3.3.4
mongoose@4.1.9
mockgoose@4.0.2

Get an error when npm install 

<img width="696" alt="screen shot 2015-09-29 at 2 33 07 pm" src="https://cloud.githubusercontent.com/assets/1058646/10175883/07720fb8-66b7-11e5-8382-f24e2c60d8e0.png">

So this seems to be an error from bunyan@1.3.6 that installs dtrace-provider@0.4.0 and fails on build

This could be solve updating bunyan dependency

**Comment by sammyisseyegh** [comment]
There's a pull request for this: https://github.com/mccormicka/Mockgoose/pull/145

**Comment by resistdesign** [comment]
Using Node 4 + Mongoose 4, `Model.create()` hangs too. Everything probably does :P

**Comment by winfinit** [comment]
I am trying a bit different approach with mockgoose, where instead of actual database mocking, i am starting in memory mongod, which is real database, and extending just a connect call of mongoose

if you would, can you please try to run same/similar tests with mockgoose "5.0.0-rc.9", and tell me issues that you are running to with this version?

**Comment by resistdesign** [comment]
@winfinit I personally wanted to use Mockgoose because we don't want to have to run the mongod process on our CI server. I guess we'll have to go a different direction. Thank you for the info :)

**Comment by winfinit** [comment]
@resistdesign 
Ryan,

what mockgoose is switching to is to use in memory storage engine, and ability to run own instance of mongod without one installing it on a system through standard package manager, purging it from time to time, and solving port collisions. for example, mockgoose 5 is now working with travis too (even tho it didn’t need to, because travis provides database within its container already). to me goal is for one not to even know or care how storage component works, i want one just to use mockgoose, and know that their tests are executed against environment that is if not identical to deployment environment, then highly similar.

i’ve noticed that people structure their tests recently just to pass, however tests have a purpose, to exercise particular logic, and if you would like to exercise your model layer, by mocking not a provided function, but actually logic that takes place in the database, then you are loosing a purpose of a unit/integration test.

so for example, if i would like to exercise some function that is providing business logic, that requires a get/find call, then it would be more appropriate to mock a get call in your test, because at the end, there isn't any value to first mock a connection call, then insert a record, and then perform a get/find call against that temporary store, where you already know what it is going to return (sinonjs could be a help there)

**Comment by resistdesign** [comment]
@winfinit I'm sold, when is the new release!?

**Comment by winfinit** [comment]
5.0 release is published, but i am still making it release candidate, because i am testing, and waiting for people to use it, before i will make it a latest release, latest rc is 10 "5.0.0-rc.10"

**Comment by resistdesign** [comment]
ah ok!

**Comment by winfinit** [comment]
5.0 is now latest, please open new issues if you will run into any problems, thank you!
