### ISSUE TITLE
Whenever i use mockgoose everything times out

### ISSUE THREAD

**Issue by joshbedo** [mccormicka/Mockgoose#157]
Came across a weird problem after trying to implement this on a personal project. It seems that when i wrap mongoose with mockgoose i get timeouts any time i try to use mongoose. Has anyone else seen this before and know of a fix? 

![](http://i.imgur.com/eGJiXyo.jpg)

**Comment by mcteo** [comment]
I cloned the repo locally to run the tests, and I get the same error. It turned out it was due to having an existing instance of mongod running already, so I think the ports conflicted (both used 27017).

What worked for me was to either stop the mongod process, or to change the port used by the library with:
```
mockgoose(mongoose, {
    port: 12345
});
```

**Comment by winfinit** [comment]
@mcteo it actually shouldn't matter, the way mockgoose is setup, is to start its own instance, and if it fails to start on a first port, it will go to next one, and so on. I just tried that on OS X, and that is what it is happening for me, what OS are you using?

**Comment by winfinit** [comment]
@joshbedo I am a bit confused with double "before" inside describe, can you try please to move connect outside of describe block?

```javascript
var should = require('chai').should();
var expect = require('chai').expect;

var Mongoose = require('mongoose').Mongoose;
var mongoose = new Mongoose();

var mockgoose = require('../Mockgoose');

var Cat = mongoose.model('Cat', { name: String });

mockgoose(mongoose);

before(function(done) {
    mongoose.connect('mongodb://example.com/TestingDB', function(err) {
        done(err);
    }); 
});

describe('User functions', function() {
	it("should create a cat foo", function(done) {
		Cat.create({name: "foo"}, function(err, cat) {
                    done(err);
		});
       });
});
```

**Comment by mcteo** [comment]
Hi @winfinit. I'm on Windows (10, x64). Your given example fails with the same exception. I stepped through some of the code using node-inspector, and found that the problem seems to be with mongodb-prebuilt. This example script fails too (the callback is never called): 
```
var mongodb_prebuilt = require('mongodb-prebuilt');
 
mongodb_prebuilt.start_server({}, function(err) {
    if (err) {
        console.log('mongod didnt start:', err);
    } else {
        console.log('mongod is started');
    }
});
```

I turned on its logging (`set DEBUG=mongodb` on Windows), and get an exception like: 
```
  mongodb 2015-11-22T16:24:59.274+0000 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory C:\data\db\ not found., terminating
2015-11-22T16:24:59.274+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
 +0ms
```
My current mongodb instance uses C:\mongodb\data\db to store its stuff, so that's the only thing like that path, but no idea how its accessing them, if its supposed to be standalone.

**Comment by joshbedo** [comment]
Yeah so the reason behind the double before is because it uses `async.waterfall` behind the scenes and will run them in order which is great for setup. I'll try moving  that out today, i ended up removing mockgoose and creating a `bootstrap.test` file i can import into my integration tests.

```js
var kraken = require('kraken-js'),
    express = require('express'),
    path = require('path'),
    mongoose = require('mongoose');

var app, mock;

before(function (done) {
    mongoose.createConnection('mongodb://localhost/test', function(err) {
        done(err);
    });
});

before(function (done) {
    app = express();
    app.on('start', done);
    app.use(kraken({
        basedir: path.resolve(__dirname, '..', '..')
    }));

    mock = app.listen(1337);
});

after(function (done) {
    mock.close(done);
});

after(function () {
  mongoose.connection.db.dropDatabase()
});

after(function (done) {
  mongoose.connection.close(done);
});

exports.mock = function() {
    return mock;
}
```

**Comment by joeltello** [comment]
i have the same issue...my test cases get stuck and eventually get a timeout...any ideas how to actually fix it using mockgoose?

**Comment by asheinfeld** [comment]
+1 here, having the same issue for all my models :(. The Cat example works though... so it's really strange
