### ISSUE TITLE
Errors cannot be displayed if mongoose.connect is called

### ISSUE THREAD

**Issue by jhen0409** [mccormicka/Mockgoose#170]
Hi all,
When I call `mockgoose(mongoose)` and `mongoose.connect(...)`, some errors will cannot be displayed. (e.g. some module not found)
I cannot trace the cause, I would like to know your views.

See following code:
```js
const mongoose = require('mongoose');
const mockgoose = require('mockgoose');

mockgoose(mongoose);
mongoose.connect('mongodb://localhost:27017/test');

// BUG: will not show `Cannot find module 'this-module-not-found'` error
require('this-module-not-found');
```

**Comment by azhang** [comment]
I'm getting this too, but it's happening with even just


```
const mockgoose = require('mockgoose');
```

**Comment by winfinit** [comment]
thank you for this bug report, issue was due to capturing of all uncaught exceptions and not re-throwing them, this is not fixed, however i didn't publish new version yet, because i am working out issue with running multiple tests with mocha, ill update this issue when new version will be published on npmjs

**Comment by azhang** [comment]
Awesome, that sounds great! I’m looking forward to seeing that fix as well (I’m running AVA as my test runner for parallel tests). Thanks for the help!

**Comment by winfinit** [comment]
this is resolved now. thank you
