### ISSUE TITLE
removal of reset

### ISSUE THREAD

**Issue by winfinit** [mccormicka/Mockgoose#187]
I am thinking to remove "reset" functionality from mockgoose, reason behind it, is that currently there are various paths that can cause failures, and also it is not what mockgoose is for, mockgoose is there to assist one with emulating/mocking database layer, and reset falls under a helper function, that is not part of mongoose or mongodb itself. 

i think such functionality needs to live either in its own module, and deal with various requests to accommodate individual scenarios.

I know that quite a few are using reset functionality, but i would like to get a feel on how upset folks would get if version 6 of mockgoose would get rid of reset.

**Comment by supersam654** [comment]
I would be unable to use mockgoose without reset (I end up calling it before every single test). I think it's a vital addition to a mocking framework because tests shouldn't need a guaranteed ordering and starting from a clean DB every time helps make that happen.

Probably very unrelated, but `expect` spies have a reset method on them to clear how many calls they have received.

If reset functionality were to be extracted into a separate module, what target group of people would be able to use mockgoose without reset?

**Comment by winfinit** [comment]
@supersam654 thank you for your feedback. Mockgoose doesnt persist data between between runs. For mocking, there are better options, such as sinonjs, or own overloading of functions that you test. Mockgoose assists with delivering identical behavior of a database that you are testing against, which mocking cannot guarantee, for example if you have aggregation pipelines, or map reduce, or any other database operations. Mockgoose also assists one to test against multiple version of mongod, which is useful in a complex environments. Another good fit is just a simple database test, without using actual own instance of mongod, or worry about mocking.

**Comment by supersam654** [comment]
I completely agree. I was actually looking into alternatives to mockgoose
before I stumbled on this thread because I was starting to feel like I
wasn't using it properly.

My only other concern then is the actual name of the project. I think there
are currently lots of people who use mockgoose to mock Mongo while testing.
Even if that isn't the intention of the project, I feel like there are many
other people like me who are using it that way. Just something to consider
when breaking a very large, if unintended, use of the project.

**Comment by supersam654** [comment]
Just wanted to follow up this. I completely redid my test suite with `sinon` and it makes a huge difference. I definitely like how the tests work now and even though I'm not currently incorporating Mockgoose anywhere, I definitely have a few small edge cases that Mockgoose would be perfect for testing. As a result, I still think that leaving in `reset()` is useful for the library as a whole.

**Comment by winfinit** [comment]
@supersam654 thank you for your comments, I don't see much complaints at the moment about reset functionality, either because it is working (based on my tests it is working) or folks gave up on it. So we will see how it goes, I dont see really anyone else complaining, so this is good.
