### ISSUE TITLE
Support matching of subdocuments and arrays using dot notation

### ISSUE THREAD

**Issue by twistedstream** [mccormicka/Mockgoose#59]
Mongoose and the MongoDB query engine allow you to match subdocuments and arrays using [a handy dot notation](http://docs.mongodb.org/manual/tutorial/query-documents/#read-operations-subdocuments):

As example, consider the following Customer documents:

``` json
[
  {
    "_id": 1,
    "name": "Joe Customer",
    "orders": [
      {
        "date": "2014-04-01T00:00:00.000Z",
        "amount": 100
      }, 
      {
        "date": "2014-04-02T00:00:00.000Z",
        "amount": 50
      }
    ]
  },
  {
    "_id": 2,
    "name": "Bob Customer",
    "orders": [
      {
        "date": "2014-04-10T00:00:00.000Z",
        "amount": 75
      }, 
      {
        "date": "2014-04-11T00:00:00.000Z",
        "amount": 25
      }
    ]
  },
  {
    "_id": 3,
    "name": "Bob Customer",
    "orders": [
      {
        "date": "2014-04-06T00:00:00.000Z",
        "amount": 100
      }
    ]
  }
]
```

We should be able find all customers who have orders with amounts = $100 with the following Mongoose code:

``` js
Customer.find({ 'orders.amount': 100 }, {}, function (err, docs) {
  // do something with the customers
});
```

Mockgoose currently doesn't support queries with this syntax.  If you use it, your queries always return zero docs.

**Comment by alexandrusavin** [comment]
I found that this issue is still valid and can be reproduce if searching for paths in a $and operator query.

So, this query should reproduce the bug:
```javascript
var query = {
    $and: [
        {
            "document.property": "value"
        }
    ]
}
```

This will not work because [AndOperation.js] (https://github.com/mccormicka/Mockgoose/blob/master/lib/operations/logical/AndOperation.js) is not aware of dot notation so everywhere model[key] is used, if the key is in dot notation, it will return undefined.

One way to fix this would be to upgrade lodash to 3.10 and use _.get and _.set methods everywhere values from the models are parsed.

PS: I've only tested it with $and operator but it might be a more general issue.
